### ISSUE TITLE
Préparer une image docker

### ISSUE THREAD

**Issue by saintmathieu** [thomaslemoine/gitflowgrp1#1]
Expliquer dans un Readme comment lancer le projet dans un conteneur tel que : 

# Foobar

## Contributing
Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.

## License
[MIT](https://choosealicense.com/licenses/mit/)

**Comment by thomaslemoine** [comment]
https://github.com/thomaslemoine/gitflowgrp1/commit/510e64b65f3523486c24a80095a4c7b00b4d8287
